### ISSUE TITLE
maxLineLength not recognized by VSCode

### ISSUE THREAD

**Issue by kevin-induro** [daidodo/format-imports#13]
**Describe the bug**
When I went to change the line length the extension considered, it was documented fine in the Wiki, but I first didn't see the option in the UI Settings in VSCode, then when I manually put the setting in the settings.json, the change took affect, but VSCode didn't recognize the setting.

**Expected behavior**
I expect VSCode to recognize this as a correct configuration. In fact, even though VSCode reports it as an unknown configuration, the configuration still takes affect appropriately.

Beyond the bug, it would seem appropriate to have this configuration show up in the UI Settings as well.

**Actual behavior**
VSCode reports the configuration setting as unknown.

**Screenshots**
![image](https://user-images.githubusercontent.com/55456841/174097731-4fd48696-23da-4087-ac2c-63cad8c1666e.png)

**OS (please complete the following information):**

- OS: Windows
- Version: 11

**Editor (please complete the following information):**

- Editor: VSCode
- Version: 1.66.2

**Comment by daidodo** [comment]
@kevin-induro Thanks for the feedback!

This is not a bug but a result of config source vs. UI settings. Config in source is recommended because it's global and under version control. You'll find more fields in [Configuration](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/Configuration.md) but not UI settings, e.g. [insertFinalNewline](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/Configuration.md#insertfinalnewline).

Another point is that most of the fields are derived from other plugins, e.g. Prettier, EditorConfig, ESLint. Ideally you shouldn't need to set them again if you have them defined already.
